version: "3.1"

services:
  app:
    image: ${REGISTRY_URI:-instantlinux}/nut-upsd:latest
    restart: always
    environment:
      SERIAL: ${UPS_1_SERIAL}
      SECRET: nut_pwd
    volumes:
      - ./ups1/ups.conf:/etc/nut/local/ups.conf:rw
    ports:
    - ${PORT_UPSD_1:-3493}:3493
    secrets:
    - nut_pwd
    privileged: true

secrets:
  nut_pwd:
    file: ./nut_pwd

